spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vacinpb
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
      platform: postgresql
server:
  port: 8081

#flyway:
#  outOfOrder: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days