spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vacinpb
    username: admin
    password: admin
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: postgresql
server:
  port: 8081
