UPDATE TABLE Employee (
    ID INT NOT NULL,
    CPF  VARCHAR NOT NULL,
    FULLNAME VARCHAR NOT NULL,
    BIRTHDATE VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    PRIMARY KEY(ID)
);