UPDATE TABLE Vaccine (
    ID INT NOT NULL,
    MANUFACTURER VARCHAR NOT NULL,
    MANUFACTUREDATE DATE NOT NULL,
    EXPIRATIONDATE DATE NOT NULL,
    LOTNUMBER VARCHAR NOT NULL,
    PRIMARY KEY(ID)
);